// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Actor struct {
	ID     int64
	UserID int64
	Name   string
	X      int64
	Y      int64
}

type Admin struct {
	ID     int64
	UserID int64
}

type Level struct {
	ID            int64
	Name          string
	AddedByUserID int64
	Added         sql.NullTime
	LastUpdated   sql.NullTime
}

type LevelsCollisionPoint struct {
	ID      int64
	LevelID int64
	X       int64
	Y       int64
}

type LevelsTscnDatum struct {
	ID       int64
	LevelID  int64
	TscnData []byte
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
}
