// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Actor struct {
	ID      int64
	UserID  int64
	Name    string
	LevelID int64
	X       int64
	Y       int64
}

type ActorsInventory struct {
	ActorID  int64
	ItemID   int64
	Quantity int64
}

type Admin struct {
	ID     int64
	UserID int64
}

type Item struct {
	ID               int64
	Name             string
	Description      string
	SpriteRegionX    int64
	SpriteRegionY    int64
	ToolPropertiesID sql.NullInt64
}

type Level struct {
	ID                  int64
	GdResPath           string
	AddedByUserID       int64
	Added               sql.NullString
	LastUpdatedByUserID int64
	LastUpdated         sql.NullString
	Foreign             interface{}
}

type LevelsCollisionPoint struct {
	ID      int64
	LevelID int64
	X       int64
	Y       int64
}

type LevelsDoor struct {
	ID                 int64
	LevelID            int64
	DestinationLevelID int64
	DestinationX       int64
	DestinationY       int64
	X                  int64
	Y                  int64
}

type LevelsGroundItem struct {
	ID             int64
	LevelID        int64
	ItemID         int64
	X              int64
	Y              int64
	RespawnSeconds int64
	Foreign        interface{}
}

type LevelsShrub struct {
	ID       int64
	LevelID  int64
	Strength int64
	X        int64
	Y        int64
}

type LevelsTscnDatum struct {
	LevelID  int64
	TscnData []byte
}

type ToolProperty struct {
	ID            int64
	Strength      int64
	LevelRequired int64
	Harvests      int64
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
}
