// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Actor struct {
	ID     int64
	UserID int64
	Name   string
	X      int64
	Y      int64
}

type Admin struct {
	ID     int64
	UserID int64
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
}
