services:
  gameserver:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ${DATA_PATH}:/gameserver/data
      - /home/t/certs:/gameserver/certs:ro

    ports:
      - "${PORT}:${PORT}" 