version: "2"
sql:
  - engine: "sqlite"
    queries: "queries.sql"
    schema: "schema.sql"
    gen:
      go:
        package: "db"
        out: "../"
        overrides:
          - column: levels.last_updated
            go_type: "int64"
          - column: levels.created_at
            go_type: "int64"
